### ISSUE TITLE
Question on library suitability 

### ISSUE THREAD

**Issue by spyhunter99** [mucaho/jnetrobust#12]
Is this library suitable for high latency and unreliable network connections?

How is reliability accomplished? Is it an ACK or a NACK based system?

**Comment by mucaho** [comment]
It's been [tested in virtual environment](https://github.com/mucaho/jnetrobust/blob/bd41b40f8d8fe935cd50f19f71aa1fc17fe6dd3e/jnetrobust-core/src/test/java/com/github/mucaho/jnetrobust/DelayedTest.java#L54) with 350 +- 50 ms ping, 10% packet loss, 5% packet dup chance. 
Worse network characteristics may be possible before the library gives up ensuring reliability for some packets, after which it tries to reestablish ordering and retransmission of newer packets.
(Although after such an event occurs you may want to handle that in application somehow).

Everything should be [explained in the wiki](https://github.com/mucaho/jnetrobust/wiki/Conceptual-Overview), if there is something unclear, please let me know.
For your specific question, it's akin to an [ACK vector reliability system](https://tools.ietf.org/html/rfc4340#section-11.4), albeit the vector bit-field acknowledges only the 33 newest received messages. That's why the message overhead (bytes) can be kept low.

**Comment by spyhunter99** [comment]
great info, thanks!

**Comment by mucaho** [comment]
Np, don't hesitate to contact me again.
It still needs testing in real, production environment though, but I hope it's a good (practical or conceptual) foundation to build upon.

**Comment by spyhunter99** [comment]
Thrilled that you have test cases by the way. I may be able to help with testing using virtual machines with [dummynet](http://info.iet.unipi.it/~luigi/dummynet/). One more question, is the communication primarily unicast, multicast or broadcast? I'm getting a sense that it's unicast based.

**Comment by mucaho** [comment]
It's unicast. You can multicast on the application layer, but yeah that's not the same.
It would complicate things a bit, but may be feasible to implement in not-so-near future :)
